/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.feedback.ide;

import ac.soton.xmark.feedback.FeedbackRuntimeModule;
import ac.soton.xmark.feedback.FeedbackStandaloneSetup;
import ac.soton.xmark.feedback.ide.FeedbackIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class FeedbackIdeSetup extends FeedbackStandaloneSetup {
  @Override
  public Injector createInjector() {
    FeedbackRuntimeModule _feedbackRuntimeModule = new FeedbackRuntimeModule();
    FeedbackIdeModule _feedbackIdeModule = new FeedbackIdeModule();
    return Guice.createInjector(Modules2.mixin(_feedbackRuntimeModule, _feedbackIdeModule));
  }
}
