/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.feedback.ide;

import ac.soton.xmark.feedback.ide.AbstractFeedbackIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class FeedbackIdeModule extends AbstractFeedbackIdeModule {
}
