/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.marking.scoping;

import ac.soton.xmark.marking.scoping.AbstractXMarkingScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class XMarkingScopeProvider extends AbstractXMarkingScopeProvider {
}
