/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.ui.tests;

import ac.soton.xmark.ui.internal.XmarkActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class XMarkingUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XmarkActivator.getInstance().getInjector("ac.soton.xmark.XMarking");
	}

}
