/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.feedback.ui.tests;

import ac.soton.xmark.feedback.ui.internal.FeedbackActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class FeedbackUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FeedbackActivator.getInstance().getInjector("ac.soton.xmark.feedback.Feedback");
	}

}
