/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.ide

import ac.soton.xmark.XMarkingRuntimeModule
import ac.soton.xmark.XMarkingStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class XMarkingIdeSetup extends XMarkingStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new XMarkingRuntimeModule, new XMarkingIdeModule))
	}
	
}
