/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.feedback.ide.contentassist.antlr;

import ac.soton.xmark.feedback.ide.contentassist.antlr.internal.InternalFeedbackParser;
import ac.soton.xmark.feedback.services.FeedbackGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class FeedbackParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(FeedbackGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, FeedbackGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getExerciseFeedbackAccess().getGroup(), "rule__ExerciseFeedback__Group__0");
			builder.put(grammarAccess.getExerciseFeedbackAccess().getGroup_3(), "rule__ExerciseFeedback__Group_3__0");
			builder.put(grammarAccess.getFeedbackAccess().getGroup(), "rule__Feedback__Group__0");
			builder.put(grammarAccess.getExerciseFeedbackAccess().getNameAssignment_2(), "rule__ExerciseFeedback__NameAssignment_2");
			builder.put(grammarAccess.getExerciseFeedbackAccess().getFeedbacksAssignment_3_0(), "rule__ExerciseFeedback__FeedbacksAssignment_3_0");
			builder.put(grammarAccess.getExerciseFeedbackAccess().getFeedbacksAssignment_3_1(), "rule__ExerciseFeedback__FeedbacksAssignment_3_1");
			builder.put(grammarAccess.getFeedbackAccess().getNameAssignment_0(), "rule__Feedback__NameAssignment_0");
			builder.put(grammarAccess.getFeedbackAccess().getRecipientsAssignment_3(), "rule__Feedback__RecipientsAssignment_3");
			builder.put(grammarAccess.getFeedbackAccess().getTitleAssignment_5(), "rule__Feedback__TitleAssignment_5");
			builder.put(grammarAccess.getFeedbackAccess().getFeedbackAssignment_7(), "rule__Feedback__FeedbackAssignment_7");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private FeedbackGrammarAccess grammarAccess;

	@Override
	protected InternalFeedbackParser createParser() {
		InternalFeedbackParser result = new InternalFeedbackParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public FeedbackGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FeedbackGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
