/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.feedback.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FeedbackAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ac/soton/xmark/feedback/parser/antlr/internal/InternalFeedback.tokens");
	}
}
