/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.feedback.parser.antlr;

import ac.soton.xmark.feedback.parser.antlr.internal.InternalFeedbackParser;
import ac.soton.xmark.feedback.services.FeedbackGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FeedbackParser extends AbstractAntlrParser {

	@Inject
	private FeedbackGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFeedbackParser createParser(XtextTokenStream stream) {
		return new InternalFeedbackParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ExerciseFeedback";
	}

	public FeedbackGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FeedbackGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
