/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.parser.antlr;

import ac.soton.xmark.parser.antlr.internal.InternalXMarkingParser;
import ac.soton.xmark.services.XMarkingGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class XMarkingParser extends AbstractAntlrParser {

	@Inject
	private XMarkingGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXMarkingParser createParser(XtextTokenStream stream) {
		return new InternalXMarkingParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Exercise";
	}

	public XMarkingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XMarkingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
