/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.feedback;

import ac.soton.xmark.feedback.AbstractFeedbackRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FeedbackRuntimeModule extends AbstractFeedbackRuntimeModule {
}
