/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.feedback;

import ac.soton.xmark.feedback.FeedbackStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FeedbackStandaloneSetup extends FeedbackStandaloneSetupGenerated {
  public static void doSetup() {
    new FeedbackStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
