/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark;

import ac.soton.xmark.AbstractXMarkingRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class XMarkingRuntimeModule extends AbstractXMarkingRuntimeModule {
}
