/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.marking.ide;

import ac.soton.xmark.marking.ide.AbstractXMarkingIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XMarkingIdeModule extends AbstractXMarkingIdeModule {
}
