/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.marking.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXMarkingScopeProvider extends DelegatingScopeProvider {
}
