/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.marking;

import ac.soton.xmark.marking.XMarkingStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class XMarkingStandaloneSetup extends XMarkingStandaloneSetupGenerated {
  public static void doSetup() {
    new XMarkingStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
