/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.marking


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XMarkingStandaloneSetup extends XMarkingStandaloneSetupGenerated {

	def static void doSetup() {
		new XMarkingStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
