/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.marking


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class XMarkingRuntimeModule extends AbstractXMarkingRuntimeModule {
}
