/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.feedback.ui.contentassist;

import ac.soton.xmark.feedback.ui.contentassist.AbstractFeedbackProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class FeedbackProposalProvider extends AbstractFeedbackProposalProvider {
}
