/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.feedback.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class FeedbackProposalProvider extends AbstractFeedbackProposalProvider {
}
