/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.ui;

import ac.soton.xmark.ui.AbstractXMarkingUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XMarkingUiModule extends AbstractXMarkingUiModule {
  public XMarkingUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
