/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.ui;

import ac.soton.xmark.ui.internal.XmarkActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XMarkingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(XmarkActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		XmarkActivator activator = XmarkActivator.getInstance();
		return activator != null ? activator.getInjector(XmarkActivator.AC_SOTON_XMARK_XMARKING) : null;
	}

}
