/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.feedback


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FeedbackStandaloneSetup extends FeedbackStandaloneSetupGenerated {

	def static void doSetup() {
		new FeedbackStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
