/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.feedback


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class FeedbackRuntimeModule extends AbstractFeedbackRuntimeModule {
}
