/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xmark.feedback.ui;

import ac.soton.xmark.feedback.ui.AbstractFeedbackUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FeedbackUiModule extends AbstractFeedbackUiModule {
  public FeedbackUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
